Title = "Notify DEMO"

[systeam]
# admin page
Admin = true

[Discord]
#Webhook link
DiscordStatus = true
WebhookLink = 'https://discordapp.com/...'

[Line]
#line
LineStatus = true
channelSecret = 'a'
channelAccessToken = 'b'